name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: swagger-ui-gen

      - name: Build and Push container image to Artifact Registry
        run: |
          gcloud builds submit \
            --tag europe-west1-docker.pkg.dev/swagger-ui-gen/api2project/api2project:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy api2project \
            --image europe-west1-docker.pkg.dev/swagger-ui-gen/api2project/api2project:latest \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --project swagger-ui-gen
